steps:
  - name: maven:3-openjdk-17
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
 
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/model-journal-348504/seng4400-a2-endpoint-1', '--build-arg=JAR_FILE=target/seng4400-a2-endpoint-1.jar', '.']

images: ['gcr.io/model-journal-348504/seng4400-a2-endpoint-1']
      